server:
  port : 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/blogPost
    username: dpicman
    password: dpicman

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
